apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bugcertsans-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bugcertsans
spec:
  secretName: bugcertsans-tls
  dnsNames: [bugcertsans.example.com]
  ipAddresses: ["10.42.0.7", "2001:db8::7"]
  uris: ["spiffe://bugcertsans.example.com/svc"]
  emailAddresses: ["ops@bugcertsans.example.com"]
  issuerRef: {name: bugcertsans-selfsigned, kind: Issuer}
